# Generated by Django 2.1.1 on 2018-09-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('address', models.TextField(verbose_name='dirección')),
                ('phone_number', models.CharField(max_length=255, verbose_name='teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='longitud')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='latitud')),
            ],
            options={
                'verbose_name': 'Información de contacto',
                'verbose_name_plural': 'Informaciones de contacto',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(max_length=255, verbose_name='teléfono')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('contacted', models.BooleanField(default=False, verbose_name='contactado')),
            ],
            options={
                'verbose_name': 'Petición de contacto',
                'verbose_name_plural': 'Peticiones de contacto',
            },
        ),
    ]
