# Generated by Django 2.0.3 on 2018-03-21 18:08

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djtools.contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinformation',
            options={'verbose_name': 'Información de contacto', 'verbose_name_plural': 'Informaciones de contacto'},
        ),
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'verbose_name': 'Petición de contacto', 'verbose_name_plural': 'Peticiones de contacto'},
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='address',
            field=models.TextField(verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='longitud'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='contacted',
            field=models.BooleanField(default=False, verbose_name='contactado'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(verbose_name='mensaje'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='teléfono'),
        ),
    ]
